import React from 'react';
import { Wheat } from 'lucide-react';
import type { Bill, BusinessSettings } from '../../types';
import { useSettings } from '../../context/SettingsContext';
import { formatCurrency, numberToWords } from '../../utils/currency';
import { formatDate, formatTime } from '../../utils/date';
import { formatPaymentMethod, formatUnit } from '../../utils/i18n';

interface A4InvoiceProps { bill: Bill; settings: BusinessSettings; isA5?: boolean; isTraditional?: boolean; }

export const A4Invoice: React.FC<A4InvoiceProps> = ({ bill, settings, isA5 = false, isTraditional = false }) => {
  const { t, language } = useSettings();
  const money = (value: number | null | undefined) => formatCurrency(value, language);
  const date = formatDate(bill.date, language);
  const time = formatTime(bill.time, language);
  const address = settings.completeAddress || [settings.addressLine1, settings.street, settings.city, settings.district, settings.state, settings.pincode].filter(Boolean).join(', ');
  const paymentLabel = formatPaymentMethod(bill.paymentMethod, language);
  return (
    <article className={`a4-invoice relative mx-auto w-full select-text overflow-hidden bg-white p-5 font-sans text-[11px] text-gray-900 shadow-lg print:m-0 print:w-full print:p-4 print:border-0 print:shadow-none ${isA5 ? 'max-w-[148mm]' : 'max-w-[210mm]'} ${isTraditional ? 'traditional-invoice' : ''}`} aria-label={`${t.invoiceTitle} ${bill.billNumber}`}>
      <div className="mb-3 border-b-2 border-primary-800 pb-3 text-center"><div className="mb-1 flex items-center justify-center gap-2 text-primary-800"><Wheat size={18} aria-hidden="true" /><span className="font-display text-xl font-bold uppercase tracking-wide">{settings.businessName || t.brandName}</span></div><p className="text-[10px] font-semibold uppercase tracking-wider text-secondary-700">{t.invoiceSubtitle}</p><p className="mt-1 text-[10px] text-gray-700">{settings.tagline || t.invoiceSubtitle}</p><div className="mt-2 flex flex-wrap justify-center gap-x-4 gap-y-1 text-[10px] font-medium"><span>{t.gstin}: <strong className="font-mono text-primary-900">{settings.gstin || '—'}</strong></span><span>{t.mobile}: <strong className="font-mono text-primary-900">{settings.mobile1 || '—'}{settings.mobile2 ? ` / ${settings.mobile2}` : ''}</strong></span></div></div>
      <div className="mb-3 flex flex-wrap items-start justify-between gap-3 border-b border-gray-200 pb-2"><div><span className="text-[10px] uppercase text-gray-500">{t.invoiceNo}:</span> <strong className="font-mono text-primary-900">{bill.billNumber}</strong><br /><span className="text-[10px] uppercase text-gray-500">{t.invoiceDate}:</span> {date} <span className="ml-2 text-[10px] uppercase text-gray-500">{t.invoiceTime}:</span> {time}</div><div className="rounded bg-primary-800 px-3 py-1 text-[10px] font-bold uppercase tracking-wider text-white">{t.invoiceTitle}</div></div>
      <section className="mb-3 grid grid-cols-2 gap-2 rounded-lg border border-primary-200 bg-primary-50/50 p-3"><div><h2 className="mb-1 text-[10px] font-bold uppercase text-primary-800">{t.billedTo}</h2><p className="font-bold uppercase">{bill.customer.name}</p>{bill.customer.mobile && <p className="text-gray-600">{t.customerMobile}: <span className="font-mono">{bill.customer.mobile}</span></p>}{bill.customer.address && <p className="text-gray-600">{t.village}: {bill.customer.address}</p>}{bill.customer.crop && <p className="text-gray-600">{t.crop}: {bill.customer.crop}</p>}{bill.customer.landArea && <p className="text-gray-600">{t.landArea}: {bill.customer.landArea}</p>}{bill.customer.gstin && <p className="text-gray-600">GSTIN: <span className="font-mono">{bill.customer.gstin}</span></p>}</div><div className="text-right"><h2 className="mb-1 text-[10px] font-bold uppercase text-primary-800">{t.paymentMode}</h2><span className="inline-block rounded border border-primary-300 bg-primary-100 px-2 py-0.5 font-bold text-primary-900">{paymentLabel}</span><p className="mt-2 text-gray-600">{t.received}: {money(bill.amountReceived)} · {t.balanceDue}: {money(bill.balance || 0)}</p></div></section>
      <table className="mb-3 w-full border-collapse border border-gray-300 text-[10px]"><thead><tr className="bg-primary-800 text-white"><th className="border border-primary-700 p-1.5 text-center">{t.itemNo}</th><th className="border border-primary-700 p-1.5 text-left">{t.agriculturalItem}</th><th className="border border-primary-700 p-1.5 text-center">{t.hsnSac}</th><th className="border border-primary-700 p-1.5 text-center">{t.qty}</th><th className="border border-primary-700 p-1.5 text-center">{t.unit}</th><th className="border border-primary-700 p-1.5 text-right">{t.rate}</th><th className="border border-primary-700 p-1.5 text-center">{t.taxPercent}</th><th className="border border-primary-700 p-1.5 text-right">{t.amount}</th></tr></thead><tbody>{bill.items.map((item, index) => <tr key={item.id || index} className={index % 2 === 0 ? 'bg-white' : 'bg-primary-50/40'}><td className="border border-gray-300 p-1.5 text-center">{index + 1}</td><td className="border border-gray-300 p-1.5 font-semibold">{item.productName}</td><td className="border border-gray-300 p-1.5 text-center font-mono">{item.hsnCode || '—'}</td><td className="border border-gray-300 p-1.5 text-center">{item.quantity}</td><td className="border border-gray-300 p-1.5 text-center">{formatUnit(item.unit, language)}</td><td className="border border-gray-300 p-1.5 text-right font-mono">{money(item.rate)}</td><td className="border border-gray-300 p-1.5 text-center">{item.gstRate}%</td><td className="border border-gray-300 p-1.5 text-right font-mono font-semibold">{money(item.totalAmount)}</td></tr>)}</tbody></table>
      <div className="grid grid-cols-12 gap-3"><div className="col-span-7 space-y-2"><div className="rounded-lg border border-gray-300 bg-gray-50 p-2.5"><p className="text-[9px] font-bold uppercase text-gray-600">{t.amountInWordsLabel}</p><p className="mt-0.5 font-serif text-xs font-bold italic text-primary-900">{numberToWords(bill.grandTotal, language)}</p></div><div className="rounded-lg border border-primary-200 bg-primary-50/60 p-2.5"><p className="text-[10px] font-bold uppercase text-primary-800">{t.scanPay}</p><p className="mt-1 font-mono text-sm font-bold text-secondary-700">8825633575@upi</p></div><div className="rounded-lg border border-gray-200 p-2 text-[9px] leading-relaxed text-gray-600"><p className="font-bold uppercase text-gray-700">{t.terms}</p><p>1. {settings.invoiceFooterMessage || t.invoiceFooter}</p><p>2. {t.termsTwo}</p><p>3. {t.termsThree}</p></div></div><div className="col-span-5 overflow-hidden rounded-lg border border-gray-300"><div className="flex justify-between bg-gray-100 px-3 py-1.5 text-[10px] font-bold"><span>{t.subtotal}</span><span>{money(bill.subtotal)}</span></div>{bill.gstMode !== 'EXEMPT' && <>{bill.cgst > 0 && <div className="flex justify-between px-3 py-1 text-[10px]"><span>{t.cgst}</span><span>{money(bill.cgst)}</span></div>}{bill.sgst > 0 && <div className="flex justify-between px-3 py-1 text-[10px]"><span>{t.sgst}</span><span>{money(bill.sgst)}</span></div>}{bill.igst > 0 && <div className="flex justify-between px-3 py-1 text-[10px]"><span>{t.igst}</span><span>{money(bill.igst)}</span></div>}</>}{bill.roundOff !== 0 && <div className="flex justify-between px-3 py-1 text-[10px]"><span>{t.roundOff}</span><span>{money(bill.roundOff)}</span></div>}<div className="flex justify-between bg-primary-800 px-3 py-2 text-xs font-bold text-white"><span>{t.totalAmount}</span><span className="font-mono">{money(bill.grandTotal)}</span></div></div></div>
      <div className="mt-4 grid grid-cols-2 gap-6 border-t border-primary-200 pt-3 text-[10px]"><div><p className="font-bold text-primary-900">{settings.businessName || t.brandName}</p><p className="mt-1 text-gray-600">{address}</p><p className="mt-1">{settings.email || ''}</p></div><div className="text-right"><p className="font-bold uppercase text-gray-700">{t.user}</p><p className="mt-5 border-t border-gray-400 pt-1 text-gray-600">{bill.createdBy}</p></div></div>
    </article>
  );
};
